frontend/controllers/HandleController.php
/**
 * This file is part of mnemosyne.
 *
 * mnemosyne is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * mnemosyne is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details
 * 
 * You should have received a copy of the GNU General Public License
 * long with mnemosyne.  If not, see <https://www.gnu.org/licenses/>.
**/

<?php

namespace frontend\controllers;

use yii\web\Controller;
use yii\filters\AccessControl;
use yii\helpers\Url;
use common\models\Handle;
use common\models\HandleSearch;
use common\models\Project;
use common\models\XrefProjectHandle;
use Yii;


class HandleController extends \yii\web\Controller
{
	/**
	 * Function handles access rules. Currently allows
	 * only authenticated users to access any handle ops
	 *
	 * @author  Ben Shirani <ben.shirani@gmail.com>
	 *
	 * @since 1.0
	 *
	 * @return array Array of access rules.
	 */
	public function behaviors()
    {
        return
		[
            'access' =>
			[
                'class' => AccessControl::className(),
                'only' => ['index', 'update', 'add', 'delete', 'getandstorenewtweets'],
                'rules' =>
				[
                    [
                        'allow' => false,
                        'actions' => ['index', 'update', 'add', 'delete', 'getandstorenewtweets'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index', 'update', 'add', 'delete', 'getandstorenewtweets'],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

	/**
	 * Index of all handles per each user
	 *
	 *
	 * @author  Ben Shirani <ben.shirani@gmail.com>
	 *
	 * @since 1.0
	 *
	 * @return  Array of access rules.
	 */
    public function actionIndex($project_id)
    {
			# Get session
			$session = Yii::$app->session;

			# Check if sessino is open
			if (!$session->isActive)
			{
				# Open Yaf_Session
				$session->open();
			}

			# Get project id
			$project_id = (integer)$project_id;

			# Sanity check: project_id is good
			if (isset($project_id) && is_int($project_id) && $project_id >= 0)
			{
				# Store project ID in session for global use
				$session->set("project_id", $project_id);

				# Get the project object
				$project = Project::find()->where(['id' => $project_id])->one();

				# Sanity: make sure we have a project
				if (!empty($project) && is_object($project) && !empty($project->id))
				{
					# Instantiate search model (empty object)
					$handleSearch = new HandleSearch();

					# Get data provider
					$handleDataProvider = $handleSearch->search($project_id, \Yii::$app->request->queryParams);

					# Build breadcrumbs
					$this->view->params['breadcrumbs'] = array();
					$this->view->params['breadcrumbs'][] = ['url' => ['project/index'], 'label' => 'Projects'];
					$this->view->params['breadcrumbs'][] = ['label' => $project->name];

					# Register Javascript
					\Yii::$app->getView()->registerJsFile(\Yii::$app->request->BaseUrl . '/js/HandleIndex.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
					\Yii::$app->getView()->registerJsFile(\Yii::$app->request->BaseUrl . '/js/Common.js', ['depends' => [\yii\web\JqueryAsset::className()]]);

					# Set variables to be passed to the view
					//$this->view->params['handleModel'] = $handleModel;
					$this->view->params['project'] = $project;
					$this->view->params['handleSearch'] = $handleSearch;
					$this->view->params['handleDataProvider'] = $handleDataProvider;
					$this->view->params['addHandleFormModel'] = new \frontend\models\AddHandleForm();

					# Return
					return $this->render('index');
				}

				# User got here by mistake (probably typed the URL in) set message
				\Yii::$app->session->setFlash('error', "Unfortunately I was unable to retrieve the tweets. Please alert the administrator!");

				# Send them back to the index
				return $this->redirect(URL::toRoute(['project/index']));
			}

			# User got here by mistake (probably typed the URL in) set message
			\Yii::$app->session->setFlash('error', "Unfortunately I was unable to complete your last request.");

			# Send them back to the index
			return $this->redirect(URL::to('index'));
    }

	public function actionUpdate()
	{
		if (\Yii::$app->request->isAjax)
		{
			# Set response type
			\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

			# Extract and sanitize request variables
			$id = base64_decode($_REQUEST['pk']);
			$id = explode(":", $id);
			$id = (int)$id[1];

			# Extract and sanitize name of property to update
			# TODO: Update this to the YII way
			$attr = trim($_REQUEST['name']);
			$attr = (string)$attr;

			# Extract and sanitize the value of the property to update
			# TODO: Update this to the YII way
			$value = trim($_REQUEST['value']);
			$value = (string)$value;

			# Instantiate model object to update
	        //$handleModel = new \app\models\Handle($id);
			$handleModel = \common\models\Handle::find()->where(['id' => $id])->one();

			# Set handle model property to new value
			$handleModel->$attr = $value;

			# Save model
			if (!empty($handleModel) && is_object($handleModel) && !empty($handleModel->id) && $handleModel->save())
			{
				# Return error
				return
				[
					'data' =>
					[
						'success' => true,
						'message' => 'Handle was saved.',
					],
					'code' => 0,
				];
			}
			else
			{
				# Return error
				return
				[
					'data' =>
					[
						'success' => false,
						'message' => 'Handle was not saved.',
					],
					'code' => -1,
				];
			}
		}

		# User got here by mistake (probably typed the URL in) set message
		\Yii::$app->session->setFlash('error', "Unfortunately I was unable to complete your last request.");

		# Send them back to the index
		return $this->redirect(URL::to('index'));
	}

	public function actionAdd()
	{
		# Sanity
		if (\Yii::$app->request->isAjax)
		{
			# Set response type
			\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

			# Instantiate form model
			$formModel = new \frontend\models\AddHandleForm();

			# Load data and validate
			if ($formModel->load(\Yii::$app->request->post()) && $formModel->validate())
			{
				# Get project Id from request payload
				$project_id = (integer)\Yii::$app->request->post("XrefProjectHandle")['project_id'];

				# Instantiate project object
				$project = \common\models\Project::find()->where(['id' => $project_id])->one();

				# Sanity check project
				if (!empty($project) && is_object($project) && !empty($project->id) && is_int($project->id))
				{
					# Add handle to project
					$result = $project->addHandleFromForm($formModel);

					# Return result
					return $result;
				}
			}

			# Return error
			return
			[
				'data' =>
				[
					'success' => false,
					'model' => $formModel,
					'message' => [$handleModel, $handleModel->getErrors()],
				],
				'code' => -1,
			];
		}

		# User got here by mistake (probably typed the URL in) set message
		\Yii::$app->session->setFlash('error', "Unfortunately I was unable to complete your last request.");

		# Send them back to the index
		return $this->redirect(URL::to('index'));
	}

	public function actionDelete()
	{
		# Sanity
		if (\Yii::$app->request->isAjax)
		{
			# Sanitize
			$handleId = (integer)$_REQUEST['id'];
			$project_id = (integer)$_REQUEST['project_id'];

			# Set response type
			\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

			# Instantiate model object
			$handleModel = \common\models\Handle::find()->where(['id' => $handleId])->one();

			# Get project handle pivot object
			$xrefProjectHandle = XrefProjectHandle::find()->where(['handle_id' => $handleModel->id, 'project_id' => $project_id])->one();

			# Delete from pivot
			if (!empty($xrefProjectHandle) && is_object($xrefProjectHandle) && !empty($xrefProjectHandle) && $xrefProjectHandle->delete())
			{
				// # Delete model (this probably should not happen here but instead a new view should serve as a master list of all handles where they can be deleted)
				// if (!empty($handleModel) && is_object($handleModel) && !empty($handleModel->id) && $handleModel->delete())
				// {

					return
					[
						'data' =>
						[
							'success' => true,
							'message' => 'Handle has been saved.',
						],
						'code' => 0,
					];
				// }
				// else
				// {
				// 	# Return error
				// 	return
				// 	[
				// 		'data' =>
				// 		[
				// 			'success' => false,
				// 			'message' => 'Handle was not saved.',
				// 		],
				// 		'code' => -1,
				// 	];
				// }
			}
		}

		# User got here by mistake (probably typed the URL in) set message
		\Yii::$app->session->setFlash('error', "Unfortunately I was unable to complete your last request.");

		# Send them back to the index
		return $this->redirect(URL::to('index'));
	}

	public function actionGetandstorenewtweets($handleId)
	{
		# Sanity
		if (\Yii::$app->request->isAjax)
		{
			# Sanitize
			$handleId = (integer)$handleId;

			# Set response type
			\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

			# Instantiate model object
			$handle = \common\models\Handle::find()->where(['id' => $handleId])->one();

			# Save model
			if (!empty($handle) && is_object($handle) && !empty($handle))
			{
				# Update tweets
				$status = $handle->updateTweets();
				
				return
				[
					'data' =>
					[
						'success' => $status,
						'message' => 'Tried to update. Check \'success\'.',
					],
					'code' => 0,
				];
			}
			else
			{
				# Return error
				return
				[
					'data' =>
					[
						'success' => false,

frontend/views/handle/index.php
/**
 * This file is part of mnemosyne.
 *
 * mnemosyne is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * mnemosyne is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details
 * 
 * You should have received a copy of the GNU General Public License
 * long with mnemosyne.  If not, see <https://www.gnu.org/licenses/>.
**/

<?php

# Use the URL namespace
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\spinner\Spinner;
use kartik\date\DatePicker;
use kartik\grid\GridView;



/* @var $this yii\web\View */
# Extract project for easy access
$project = $this->params['project'];

# Show what project user is working in
echo "<h1>$project->name</h1>";

/*****************************************
* Add handle form
******************************************/
$addHandleForm = ActiveForm::begin([
    'action' => ['handle/add'],
    'id' => 'add-handle-form',
    'options' => ['class' => 'form-horizontal'],
]);

?>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6" style="width: 160px;">
            <?php echo $addHandleForm->field($this->params['addHandleFormModel'], 'handle')->textInput(['style'=>'width:150px']); ?>
        </div>
        <div class="col-sm-6" style="width: 155px;">
            <?php echo $addHandleForm->field($this->params['addHandleFormModel'], 'label')->textInput(['style'=>'width:150px']); ?>
        </div>
        <div class="col-sm-6 pull-bottom" style="width: 155px;">
            <?php //echo $addCategoryForm->submit(); ?>
            <div class="form-group field-category-name required" style="padding-top: 27px">
                <!-- <label class="control-label"></label> -->
                <?php echo Html::hiddenInput('XrefProjectHandle[project_id]', $this->params['project']->id); ?>
                <?php echo Html::submitButton('Add Handle', ['class' => 'btn btn-primary', 'id' => 'addHandleBtnNoSpinner']) ?>
                <?php

                    echo '<button class="btn btn-primary hidden" id="addHandleBtnWithSpinner">';
                        echo Spinner::widget(['preset' => 'tiny', 'align' => 'right', 'caption' => 'Add Handle']);
                    echo '</button>';

                ?>
                <div class="help-block"></div>
            </div>
        </div>
    </div>
</div>
<?php
ActiveForm::end();

echo "<a href='".Url::toRoute(['handle/index'])."' style='margin-bottom: 20px;'><button id='clearFilterBtn' data-refreshUrl='".Url::toRoute(['handle/index'])."' class='btn btn-primary' style='float: right; margin-bottom: 10px; margin-right: 10px;'>Clear Filters</button></a>";
echo "<br />";
echo "<br />";
echo "<br />";




\yii\widgets\Pjax::begin();
echo kartik\grid\GridView::widget(
//echo \yii\grid\GridView::widget(
[

  # Set ID
  'id' => 'handle-grid',

	# Set dataprovider
  'dataProvider' => $this->params['handleDataProvider'],
  'filterModel' => $this->params['handleSearch'],

	# Define columns
	'columns' =>
	[
		# Editable Handle
		[
			'class' => \yii2mod\editable\EditableColumn::class,
			'attribute' => 'handle',
			'url' => ['handle/update'],
		],

        # Label
        [
            'class' => \yii2mod\editable\EditableColumn::class,
            'attribute' => 'label',
            'url' => ['handle/update'],
        ],

		# Name
        'name',
        'user_since',
        'numTweets',

        # View Tweets
        [
            'label' => 'View Tweets',
            'format' => 'raw',
            'value' => function ($model)
            {
                // return Html::a('View Tweets', ['tweet/index', 'handleId' => $model->id], ['data-pjax' => 0, 'target' => '_blank']);
                return Html::a('View Tweets', ['tweet/index', 'handleId' => $model->id], ['data-pjax' => "0"]);

            }
        ],

        # Delete
        [
            //'data-key' => function($data) {return $data->id;},
            'class' => 'yii\grid\ActionColumn',
            'template' => '{delete}',
            'buttons' =>
            [
                'delete' => function () use ($project)
                {
                    return Html::a('<span class="glyphicon glyphicon-trash"></span>', true,
                    [
                        'class' => 'pjax-delete-link',
                        //'handle-id' => $data['id'],
                        //'delete-url' => Url::toRoute('handle/delete'),
                        'delete-url' => Url::toRoute(['handle/delete', 'project_id' => $project->id]),
                        'pjax-container' => 'handle-grid',
                        'title' => Yii::t('yii', 'Delete')
                    ]);
                },
            ]
        ]
	]
]);
\yii\widgets\Pjax::end();

?>