common/models/Category.php
/**
 * This file is part of mnemosyne.
 *
 * mnemosyne is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * mnemosyne is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details
 * 
 * You should have received a copy of the GNU General Public License
 * long with mnemosyne.  If not, see <https://www.gnu.org/licenses/>.
**/

<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "category".
 *
 * @property int $id
 * @property int $user_id
 * @property string $name
 * @property string $display_name
 *
 * @property User $user
 * @property CategoryOption[] $categoryOptions
 */
class Category extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'name', 'project_id'], 'required'],
            [['user_id', 'project_id'], 'integer'],
            [['name', 'display_name'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'name' => 'Name',
            'display_name' => 'Display Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategoryOptions()
    {
        return $this->hasMany(CategoryOption::className(), ['category_id' => 'id']);
    }
}

frontend/models/CategoryForm.php
/**
 * This file is part of mnemosyne.
 *
 * mnemosyne is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * mnemosyne is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details
 * 
 * You should have received a copy of the GNU General Public License
 * long with mnemosyne.  If not, see <https://www.gnu.org/licenses/>.
**/

<?php

namespace frontend\models;

class CategoryForm extends \yii\base\Model
{
    public $name;
    public $options;

    public function rules()
    {
        # Array of rules
        return
        [
          # Required to load
          [['AddCategoryForm'], 'safe'],

        ];
    }
}

frontend/controllers/CategoryController.php
/**
 * This file is part of mnemosyne.
 *
 * mnemosyne is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * mnemosyne is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details
 * 
 * You should have received a copy of the GNU General Public License
 * long with mnemosyne.  If not, see <https://www.gnu.org/licenses/>.
**/

<?php

# Define namespace
namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\helpers\Url;
use common\models\Category;
use frontend\models\CategoryForm;
use common\models\Handle;


class CategoryController extends \yii\web\Controller
{
    /**
	 * Function handles access rules. Currently allows
	 * only authenticated users to access any handle ops
	 *
	 * @author  Ben Shirani <ben.shirani@gmail.com>
	 *
	 * @since 1.0
	 *
	 * @return array Array of access rules.
	 */
	public function behaviors()
    {
        return
		[
            'access' =>
			[
                'class' => AccessControl::className(),
                'only' => ['index', 'update', 'add', 'delete'],
                'rules' =>
				[
                    [
                        'allow' => false,
                        'actions' => ['index', 'update', 'add', 'delete'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index', 'update', 'add', 'delete'],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionAdd()
    {
			# Sanity
			if (\Yii::$app->request->isAjax)
			{
				# Set response type
				\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

				# Instantiate form model
				$category = new Category();

				# Load data and validate
				if ($category->load(\Yii::$app->request->post()))
				{
	        # Assign to current user
					$category->user_id = \Yii::$app->user->id;

					# Save model
					if ($category->validate() && $category->save())
					{
						# Return data to page
						return
						[
								'data' =>
								[
									'success' => true,
									'model' => $category,
									'message' => 'Category has been saved.',
								],
								'code' => 0,
							];
						}
					}

					# Return error
					return
					[
						'data' =>
						[
							'success' => false,
							'model' => $category,
							'message' => 'Category was not saved.',
						],
						'code' => -1,
					];
			}

			# User got here by mistake (probably typed the URL in) set message
			\Yii::$app->session->setFlash('error', "Unfortunately I was unable to complete your last request.");

			# Send them back to the index
			return $this->redirect(URL::to('index'));
    }

    public function actionDelete()
    {
        if (\Yii::$app->request->isAjax)
		{
			# Sanitize
			$categoryId = (integer)$_REQUEST['id'];

			# Set response type
			\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

			# Instantiate model object
			$category = Category::find()->where(['id' => $categoryId])->one();

			# Save model
			if (!empty($category) && is_object($category) && !empty($category->id) && $category->delete())
			{
				return
				[
					'data' =>
					[
						'success' => true,
						'message' => 'Category has been deleted.',
					],
					'code' => 0,
				];
			}
			else
			{
				# Return error
				return
				[
					'data' =>
					[
						'success' => false,
						'message' => $category->getErrors(),
					],
					'code' => -1,
				];
			}
		}

		# User got here by mistake (probably typed the URL in) set message
		\Yii::$app->session->setFlash('error', "Unfortunately I was unable to complete your last request.");

		# Send them back to the index
		return $this->redirect(URL::to('index'));
    }

		public function actionIndex()
    {
				# Get session
				$session = Yii::$app->session;

				# Check for active session
				if ($session->isActive)
				{
					# Get project id
					$project_id = $session->get("project_id");

					# Sanity check project id
					if (isset($project_id) && $project_id != null && is_int($project_id) && $project_id >= 0)
					{
						# Get project object
						$project = \common\models\Project::find()->where(['id' => $project_id])->one();

						# Instantiate data provider
						$categoryDataProvider = new \yii\data\ActiveDataProvider(
						[
							// 'query' => Category::find()->where(['user_id' => \Yii::$app->user->id]),
							'query' => Category::find()->where(["project_id" => $project_id]),
							'pagination' =>
							[
								'pageSize' => 20,
							],
						]);

						# Instantiate Category Object
		        $category = new Category();

		        # Instantiate form to collect information
		        $categoryForm = new CategoryForm();

		        # Register Javascript
		        \Yii::$app->getView()->registerJsFile(\Yii::$app->request->BaseUrl . '/js/CategoryIndex.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
		        \Yii::$app->getView()->registerJsFile(\Yii::$app->request->BaseUrl . '/js/Common.js', ['depends' => [\yii\web\JqueryAsset::className()]]);

						# Build breadcrumbs
						$this->view->params['breadcrumbs'] = array();
						$this->view->params['breadcrumbs'][] = ['url' => ['project/index'], 'label' => 'Projects'];
						$this->view->params['breadcrumbs'][] = ['url' => ['handle/index', 'project_id' => $project_id], 'label' => $project->name];
						$this->view->params['breadcrumbs'][] = ['label' => "Categories"];

		        # Send data to view
						$this->view->params['project_id'] = $project_id;
		        $this->view->params['category'] = $category;
		        $this->view->params['categoryForm'] = $categoryForm;
		        $this->view->params['categoryDataProvider'] = $categoryDataProvider;

		        # Display page
		        return $this->render('index');
					}
				}

				# User got here by mistake (probably typed the URL in) set message
				\Yii::$app->session->setFlash('error', "Unfortunately I was unable to retrieve the webpage. Please alert the administrator!");

				# Send them back to the index
				return $this->redirect(URL::toRoute(['project/index']));
    }


    public function actionUpdate()
    {
        if (\Yii::$app->request->isAjax)
        {
            # Set response type
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

            # Extract and sanitize request variables
            $id = base64_decode($_REQUEST['pk']);
            $id = explode(":", $id);
            $id = (int)$id[1];

            # Extract and sanitize name of property to update
            # TODO: Update this to the YII way
            $attr = trim($_REQUEST['name']);
            $attr = (string)$attr;

            # Extract and sanitize the value of the property to update
            # TODO: Update this to the YII way
            $value = trim($_REQUEST['value']);
            $value = (string)$value;

            # Instantiate model object to update
            $category = \common\models\Category::find()->where(['id' => $id])->one();

            # Set handle model property to new value
            $category->$attr = $value;

            # Save model
            if (!empty($category) && is_object($category) && !empty($category->id) && $category->save())
            {
                # Return error
                return
                [
                    'data' =>
                    [
                        'success' => true,
                        'message' => 'Category was saved.',
                    ],
                    'code' => 0,
                ];
            }
            else
            {
                # Return error
                return
                [
                    'data' =>
                    [
                        'success' => false,
                        'message' => 'Category was not saved.',
                    ],
                    'code' => -1,
                ];
            }
        }

        # User got here by mistake (probably typed the URL in) set message
        \Yii::$app->session->setFlash('error', "Unfortunately I was unable to complete your last request.");

        # Send them back to the index
        return $this->redirect(URL::to('index'));
        //return $this->render('update');
    }
}

frontend/views/category/add.php
/**
 * This file is part of mnemosyne.
 *
 * mnemosyne is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * mnemosyne is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details
 * 
 * You should have received a copy of the GNU General Public License
 * long with mnemosyne.  If not, see <https://www.gnu.org/licenses/>.
**/

<?php
/* @var $this yii\web\View */

# Use the URL namespace
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>
<h1>category/add</h1>

<?php
/*****************************************
* Add handle form
******************************************/
$addCategoryForm = ActiveForm::begin(
[
    'action' => ['category/add'],
    'id' => 'add-category-form',
    'options' => ['class' => 'form-horizontal'],
]);

?>
<div class="row">
    <div class="col-sm-6" style="width: 160px;">
        <?php echo $addCategoryForm->field($this->params['category'], 'name')->textInput(['style'=>'width:150px']); ?>
    </div>
    <div class="col-sm-6" style="width: 155px;">
        <?php echo $addCategoryForm->field($this->params['addHandleFormModel'], 'label')->textInput(['style'=>'width:150px']); ?>
    </div>
</div>



<div class="form-group">
      <!-- //Html::submitButton(Yii::t('app', 'add_handle'), ['class' => 'btn btn-primary']) -->
      <?= Html::submitButton('Add Handle', ['class' => 'btn btn-primary']) ?>
</div>
<?php
ActiveForm::end();

frontend/views/category/index.php
/**
 * This file is part of mnemosyne.
 *
 * mnemosyne is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * mnemosyne is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details
 * 
 * You should have received a copy of the GNU General Public License
 * long with mnemosyne.  If not, see <https://www.gnu.org/licenses/>.
**/

<?php

/* @var $this yii\web\View */

# Use the URL namespace
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;


# Display a title
echo "<h1>Coding Categories</h1>";

/*****************************************
* Add handle form
******************************************/
$addCategoryForm = ActiveForm::begin(
[
    'action' => ['category/add'],
    'id' => 'add-category-form',
    'options' => ['class' => 'form-horizontal'],
]);


?>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6" style="width: 160px;">
            <?php echo $addCategoryForm->field($this->params['category'], 'name')->textInput(['style'=>'width:150px']); ?>
        </div>
        <div class="col-sm-6" style="width: 155px;">
            <?php echo $addCategoryForm->field($this->params['category'], 'display_name')->textInput(['style'=>'width:150px']); ?>
        </div>
        <div class="col-sm-6 pull-bottom" style="width: 155px;">
            <?php //echo $addCategoryForm->submit(); ?>
            <div class="form-group field-category-name required" style="padding-top: 27px">
                <!-- <label class="control-label"></label> -->
                <?php echo Html::hiddenInput('Category[project_id]', $this->params['project_id']); ?>
                <?php echo Html::submitButton('Add category', ['class' => 'btn btn-primary']) ?>
                <div class="help-block"></div>
            </div>
        </div>
    </div>
</div>
<?php
ActiveForm::end();


\yii\widgets\Pjax::begin();
//\yii\widgets\Pjax::widget(['id' => 'formsection']);
echo \yii\grid\GridView::widget(
[
  'id' => 'category-grid',
  'dataProvider' => $this->params['categoryDataProvider'],
  'columns' =>
  [
      'id',
      'user_id',
      //'name',
      [
          'class' => \yii2mod\editable\EditableColumn::class,
          'attribute' => 'name',
          'url' => ['category/update'],
      ],
      [
          'class' => \yii2mod\editable\EditableColumn::class,
          'attribute' => 'display_name',
          'url' => ['category/update'],
      ],
      //'display_name',
      [
          'label' => 'Options',
          'format' => 'raw',
          'value' => function ($model)
          {
              # Define output
              $output = "";

              # Pull options
              $categoryOptions = $model->getCategoryOptions()->all();

              # Check to make sure we have some
              if (count($categoryOptions))
              {
                  # Loop through options and add to output
                  foreach ($categoryOptions as $ndx => $categoryOption)
                  {

                      //$output .= "<li>".$categoryOption->name."</li>";
                      $output .= "<li>".$categoryOption->code." - ".$categoryOption->name."</li>";
                  }
              }
              else
              {
                  $output = "Add Options";
              }

              # Finish output tag
              //$output = "</ol>";
              //return $output;
              return Html::a($output, ['categoryoption/index', 'categoryId' => $model->id], ['data-pjax' => 0]);
          }
      ],
      # Delete
      [
          //'data-key' => function($data) {return $data->id;},
          'class' => 'yii\grid\ActionColumn',
          'template' => '{delete}',
          'buttons' =>
          [
              'delete' => function ()
              {
                  return Html::a('<span class="glyphicon glyphicon-trash"></span>', true,
                  [
                      'class' => 'pjax-delete-link',
                      //'handle-id' => $data['id'],
                      'delete-url' => Url::toRoute('category/delete'),
                      'pjax-container' => 'category-grid',
                      'title' => Yii::t('yii', 'Delete')
                  ]);
              },
          ]
      ]

  ]
]);
\yii\widgets\Pjax::end();

?>