common/models/CategoryOption.php
/**
 * This file is part of mnemosyne.
 *
 * mnemosyne is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * mnemosyne is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details
 * 
 * You should have received a copy of the GNU General Public License
 * long with mnemosyne.  If not, see <https://www.gnu.org/licenses/>.
**/

<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "category_option".
 *
 * @property int $id
 * @property int $category_id
 * @property int $code
 * @property string $name
 * @property string $description
 *
 * @property Category $category
 * @property CategoryOptionValue[] $categoryOptionValues
 * @property CategorySubOption[] $categorySubOptions
 */
class CategoryOption extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'category_option';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['category_id', 'code', 'name'], 'required'],
            [['category_id', 'code'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['description'], 'string', 'max' => 500],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['category_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category_id' => 'Category ID',
            'code' => 'Code',
            'name' => 'Name',
            'description' => 'Description',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategoryOptionValues()
    {
        return $this->hasMany(CategoryOptionValue::className(), ['category_option_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategorySubOptions()
    {
        return $this->hasMany(CategorySubOption::className(), ['category_option_id' => 'id']);
    }
}

frontend/controllers/CategoryoptionController.php
/**
 * This file is part of mnemosyne.
 *
 * mnemosyne is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * mnemosyne is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details
 * 
 * You should have received a copy of the GNU General Public License
 * long with mnemosyne.  If not, see <https://www.gnu.org/licenses/>.
**/

<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\helpers\Url;
use common\models\Category;
use common\models\CategoryOption;


class CategoryoptionController extends \yii\web\Controller
{
    /**
     * Function handles access rules. Currently allows
     * only authenticated users to access any handle ops
     *
     * @author  Ben Shirani <ben.shirani@gmail.com>
     *
     * @since 1.0
     *
     * @return array Array of access rules.
     */
    public function behaviors()
    {
        return
        [
            'access' =>
            [
                'class' => AccessControl::className(),
                'only' => ['index', 'update', 'add', 'delete'],
                'rules' =>
                [
                    [
                        'allow' => false,
                        'actions' => ['index', 'update', 'add', 'delete'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index', 'update', 'add', 'delete'],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionAdd()
    {
        # Sanity
		if (\Yii::$app->request->isAjax)
		{
			# Set response type
			\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

			# Instantiate form model
			$categoryOption = new CategoryOption();

			# Load data and validate
			if ($categoryOption->load(\Yii::$app->request->post()))
			{
				# Save model
				if ($categoryOption->validate() && $categoryOption->save())
				{
					# Return data to page
					return [
							'data' => [
									'success' => true,
									'model' => $categoryOption,
									'message' => 'Category has been saved.',
							],
							'code' => 0,
					];
				}
			}

			# Return error
			return
			[
				'data' =>
				[
					'success' => false,
					'model' => $categoryOption,
					'message' => $categoryOption->getErrors(),
				],
				'code' => -1,
			];
		}

		# User got here by mistake (probably typed the URL in) set message
		\Yii::$app->session->setFlash('error', "Unfortunately I was unable to complete your last request.");

		# Send them back to the index
		return $this->redirect(URL::to('index'));
    }

    public function actionDelete()
    {
        if (\Yii::$app->request->isAjax)
		{
			# Sanitize
			$categoryOptionId = (integer)$_REQUEST['id'];

			# Set response type
			\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

			# Instantiate model object
			$categoryOption = CategoryOption::find()->where(['id' => $categoryOptionId])->one();

			# Save model
			if (!empty($categoryOption) && is_object($categoryOption) && !empty($categoryOption->id) && $categoryOption->delete())
			{
				return
				[
					'data' =>
					[
						'success' => true,
						'message' => 'Category Option has been deleted.',
					],
					'code' => 0,
				];
			}
			else
			{
				# Return error
				return
				[
					'data' =>
					[
						'success' => false,
						'message' => $categoryOption->getErrors(),
					],
					'code' => -1,
				];
			}
		}

		# User got here by mistake (probably typed the URL in) set message
		\Yii::$app->session->setFlash('error', "Unfortunately I was unable to complete your last request.");

		# Send them back to the index
		return $this->redirect(URL::to('index'));
    }

    public function actionIndex($categoryId)
    {
      # Get session
      $session = Yii::$app->session;

      # Sanity check session
      if ($session->isActive)
      {
        # Get the project id from the session
        $project_id = $session->get("project_id");

        # Sanity check project
        if (isset($project_id) && is_int($project_id) && $project_id >= 0)
        {
          # Get project object
          $project = \common\models\Project::find()->where(['id' => $project_id])->one();

            # Instantiate data provider
            $categoryOptionDataProvider = new \yii\data\ActiveDataProvider(
            [
                'query' => CategoryOption::find()->where(['category_id' => $categoryId]),
                'pagination' =>
                [
                    'pageSize' => 20,
                 ],
            ]);

            # Instantiate Category Object
            $category = Category::find()->where(['id' => $categoryId])->one();
            $categoryOption = new CategoryOption();
            $categoryOptions = CategoryOption::find()->where(['category_id' => $categoryId])->all();

            # Register Javascript
            \Yii::$app->getView()->registerJsFile(\Yii::$app->request->BaseUrl . '/js/CategoryOptionIndex.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
            \Yii::$app->getView()->registerJsFile(\Yii::$app->request->BaseUrl . '/js/Common.js', ['depends' => [\yii\web\JqueryAsset::className()]]);

            # Build breadcrumbs
            $this->view->params['breadcrumbs'] = array();
            $this->view->params['breadcrumbs'][] = ['url' => ['project/index'], 'label' => 'Projects'];
            $this->view->params['breadcrumbs'][] = ['url' => ['handle/index', 'project_id' => $project_id], 'label' => $project->name];
            $this->view->params['breadcrumbs'][] = ['url' => ['category/index'], 'label' => 'Categories'];
            $this->view->params['breadcrumbs'][] = ['label' => $category->name];

            # Send data to view
            $this->view->params['category'] = $category;
            $this->view->params['categoryOption'] = $categoryOption;
            $this->view->params['categoryOptions'] = $categoryOptions;
            $this->view->params['categoryOptionDataProvider'] = $categoryOptionDataProvider;

            # Display page
            return $this->render('index');
          }
        }

        # User got here by mistake (probably typed the URL in) set message
        \Yii::$app->session->setFlash('error', "Unfortunately I was unable to retrieve the webpage. Please alert the administrator!");

        # Send them back to the index
        return $this->redirect(URL::toRoute(['project/index']));
    }

    public function actionUpdate()
    {
        if (\Yii::$app->request->isAjax)
        {
            # Set response type
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

            # Extract and sanitize request variables
            $id = base64_decode($_REQUEST['pk']);
            $id = explode(":", $id);
            $id = (int)$id[1];

            # Extract and sanitize name of property to update
            # TODO: Update this to the YII way
            $attr = trim($_REQUEST['name']);
            $attr = (string)$attr;

            # Extract and sanitize the value of the property to update
            # TODO: Update this to the YII way
            $value = trim($_REQUEST['value']);
            $value = (string)$value;

            # Instantiate model object to update
            $categoryOption = \common\models\CategoryOption::find()->where(['id' => $id])->one();

            # Set handle model property to new value
            $categoryOption->$attr = $value;

            # Save model
            if (!empty($categoryOption) && is_object($categoryOption) && !empty($categoryOption->id) && $categoryOption->save())
            {
                # Return error
                return
                [
                    'data' =>
                    [
                        'success' => true,
                        'message' => 'Category Option was saved.',
                    ],
                    'code' => 0,
                ];
            }
            else
            {
                # Return error
                return
                [
                    'data' =>
                    [
                        'success' => false,
                        'message' => $categoryOption->getErrors(),
                    ],
                    'code' => -1,
                ];
            }
        }

        # User got here by mistake (probably typed the URL in) set message
        \Yii::$app->session->setFlash('error', "Unfortunately I was unable to complete your last request.");

        # Send them back to the index
        return $this->redirect(URL::to('index'));
        //return $this->render('update');
    }
}

frontend/views/categoryoption/index.php
/**
 * This file is part of mnemosyne.
 *
 * mnemosyne is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * mnemosyne is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details
 * 
 * You should have received a copy of the GNU General Public License
 * long with mnemosyne.  If not, see <https://www.gnu.org/licenses/>.
**/

<?php

/* @var $this yii\web\View */

# Use the URL namespace
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

echo "<h1>".$this->params['category']->display_name."</h1>";

/* @var $this yii\web\View */
/*****************************************
* Add handle form
******************************************/
$addCategoryOptionForm = ActiveForm::begin(
[
    'action' => ['categoryoption/add'],
    'id' => 'add-category-option-form',
    'options' => ['class' => 'form-horizontal'],
]);


?>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6" style="width: 160px;">
            <?php echo $addCategoryOptionForm->field($this->params['categoryOption'], 'code')->textInput(['style'=>'width:150px']); ?>
        </div>
        <div class="col-sm-6" style="width: 155px;">
            <?php echo $addCategoryOptionForm->field($this->params['categoryOption'], 'name')->textInput(['style'=>'width:150px']); ?>
        </div>
        <div class="col-sm-6" style="width: 355px;">
            <?php echo $addCategoryOptionForm->field($this->params['categoryOption'], 'description')->textInput(['style'=>'width:350px']); ?>
        </div>
        <div class="col-sm-6 pull-bottom" style="width: 155px;">
            <?php //echo $addCategoryForm->submit(); ?>
            <div class="form-group field-category-name required" style="padding-top: 27px">
                <!-- <label class="control-label"></label> -->
                <?php
                    echo Html::hiddenInput('CategoryOption[category_id]', $this->params['category']->id);
                    //echo $addCategoryOptionForm->field($this->params['categoryOption'], 'category_id')->hiddenInput();
                ?>
                <?php echo Html::submitButton('Add Category Option', ['class' => 'btn btn-primary']) ?>
                <div class="help-block"></div>
            </div>
        </div>
    </div>
</div>
<?php
ActiveForm::end();





\yii\widgets\Pjax::begin();
//\yii\widgets\Pjax::widget(['id' => 'formsection']);
echo \yii\grid\GridView::widget(
[
  'id' => 'category-option-grid',
  'dataProvider' => $this->params['categoryOptionDataProvider'],
  'columns' =>
  [
      'id',
      [
          'class' => \yii2mod\editable\EditableColumn::class,
          'attribute' => 'code',
          'url' => ['categoryoption/update'],
      ],
      [
          'class' => \yii2mod\editable\EditableColumn::class,
          'attribute' => 'name',
          'url' => ['categoryoption/update'],
      ],
      [
          'class' => \yii2mod\editable\EditableColumn::class,
          'attribute' => 'description',
          'url' => ['categoryoption/update'],
      ],
      # Category sub options
      [
          'label' => 'Sub Options',
          'format' => 'raw',
          'value' => function ($model)
          {
              $output = "Click here to create sub options";
              $categorySubOptions = $model->getCategorySubOptions()->all();
              if (count($categorySubOptions))
              {
                  $output = "";
                  foreach($categorySubOptions as $categorySubOption)
                  {
                      $output .= "<li><span style='display: inline-block; font-size: 90%;''>".$categorySubOption->name." (".$categorySubOption->code.")</span></li>";
                  }
              }

              # Return
              return Html::a($output, ['categorysuboption/index', 'category_option_id' => $model->id], ['data-pjax' => 0]);
              //return $output;
          }
      ],
      # Delete
      [
          //'data-key' => function($data) {return $data->id;},
          'class' => 'yii\grid\ActionColumn',
          'template' => '{delete}',
          'buttons' =>
          [
              'delete' => function ()
              {
                  return Html::a('<span class="glyphicon glyphicon-trash"></span>', true,
                  [
                      'class' => 'pjax-delete-link',
                      //'handle-id' => $data['id'],
                      'delete-url' => Url::toRoute('categoryoption/delete'),
                      'pjax-container' => 'category-option-grid',
                      'title' => Yii::t('yii', 'Delete')
                  ]);
              },
          ]
      ]
  ]
]);
\yii\widgets\Pjax::end();

?>