common/models/Group.php
/**
 * This file is part of mnemosyne.
 *
 * mnemosyne is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * mnemosyne is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details
 * 
 * You should have received a copy of the GNU General Public License
 * long with mnemosyne.  If not, see <https://www.gnu.org/licenses/>.
**/

<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "group".
 *
 * @property int $id
 * @property string $name
 * @property string $description
 *
 * @property GroupMember[] $groupMembers
 */
class Group extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'group';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['description'], 'string'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroupMembers()
    {
        return $this->hasMany(GroupMember::className(), ['group_id' => 'id']);
    }
}

frontend/controllers/GroupController.php
/**
 * This file is part of mnemosyne.
 *
 * mnemosyne is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * mnemosyne is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details
 * 
 * You should have received a copy of the GNU General Public License
 * long with mnemosyne.  If not, see <https://www.gnu.org/licenses/>.
**/

<?php

namespace frontend\controllers;

use yii\filters\AccessControl;
use common\models\Group;


class GroupController extends \yii\web\Controller
{
    /**
     * Function handles access rules. Currently allows
     * only authenticated users to access any handle ops
     *
     * @author  Ben Shirani <ben.shirani@gmail.com>
     *
     * @since 1.0
     *
     * @return array Array of access rules.
     */
    public function behaviors()
    {
        return
        [
            'access' =>
            [
                'class' => AccessControl::className(),
                'only' => ['index', 'update', 'add', 'delete'],
                'rules' =>
                [
                    [
                        'allow' => false,
                        'actions' => ['index', 'update', 'add', 'delete'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index', 'update', 'add', 'delete'],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Index of all groups per each user
     *
     *
     * @author  Ben Shirani <ben.shirani@gmail.com>
     *
     * @since 1.0
     *
     * @return  Array of access rules.
     */
    public function actionIndex()
    {
        # Instantiate data provider
        $groupDataProvider = new \yii\data\ActiveDataProvider(
        [
            'query' => \common\models\Group::find()->where(['admin_id' => \Yii::$app->user->id]),
            'pagination' =>
            [
                'pageSize' => 20,
             ],
        ]);

        # Instantiate an empty group
        $group = new Group();

        # Register Javascript
        \Yii::$app->getView()->registerJsFile(\Yii::$app->request->BaseUrl . '/js/GroupIndex.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
        \Yii::$app->getView()->registerJsFile(\Yii::$app->request->BaseUrl . '/js/Common.js', ['depends' => [\yii\web\JqueryAsset::className()]]);


        # Set variables to be passed to the view
        $this->view->params['groupDataProvider'] = $groupDataProvider;
        $this->view->params['group'] = $group;

        # Return
        return $this->render('index');
    }

    public function actionAdd()
    {
        # Sanity Check
        if (\Yii::$app->request->isAjax)
        {
            # Set response type
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

            # Instantiate form model
            $group = new Group();

            # Load data and validate
            if ($group->load(\Yii::$app->request->post()))
            {
                # Assign to current user
                $group->admin_id = \Yii::$app->user->id;

                # Save model
                if ($group->validate() && $group->save())
                {
                    # Return data to page
                    return [
                            'data' => [
                                    'success' => true,
                                    'model' => $group,
                                    'message' => 'Category has been saved.',
                            ],
                            'code' => 0,
                    ];
                }
            }

            # Return error
            return
            [
                'data' =>
                [
                    'success' => false,
                    'model' => $group,
                    'message' => $group->getErrors(),
                ],
                'code' => -1,
            ];
        }

        # User got here by mistake (probably typed the URL in) set message
        \Yii::$app->session->setFlash('error', "Unfortunately I was unable to complete your last request.");

        # Send them back to the index
        return $this->redirect(URL::to('index'));
    }

    public function actionDelete()
    {
        # Sanity
		if (\Yii::$app->request->isAjax)
		{
			# Sanitize
			$groupId = (integer)$_REQUEST['id'];

			# Set response type
			\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

			# Instantiate model object
			$group = \common\models\Group::find()->where(['id' => $groupId])->one();

			# Save model
			if (!empty($group) && is_object($group) && !empty($group->id) && $group->delete())
			{
				return
				[
					'data' =>
					[
						'success' => true,
						'message' => 'Group has been deleted.',
					],
					'code' => 0,
				];
			}
			else
			{
				# Return error
				return
				[
					'data' =>
					[
						'success' => false,
						'message' => 'Group was not not saved.',
					],
					'code' => -1,
				];
			}
		}

		# User got here by mistake (probably typed the URL in) set message
		\Yii::$app->session->setFlash('error', "Unfortunately I was unable to complete your last request.");

		# Send them back to the index
		return $this->redirect(URL::to('index'));
    }

    public function actionUpdate()
    {
        if (\Yii::$app->request->isAjax)
        {
            # Set response type
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

            # Extract and sanitize request variables
            $id = base64_decode($_REQUEST['pk']);
            $id = explode(":", $id);
            $id = (int)$id[1];

            # Extract and sanitize name of property to update
            # TODO: Update this to the YII way
            $attr = trim($_REQUEST['name']);
            $attr = (string)$attr;

            # Extract and sanitize the value of the property to update
            # TODO: Update this to the YII way
            $value = trim($_REQUEST['value']);
            $value = (string)$value;

            # Instantiate model object to update
            $group = \common\models\Group::find()->where(['id' => $id])->one();

            # Set handle model property to new value
            $group->$attr = $value;

            # Save model
            if (!empty($group) && is_object($group) && !empty($group->id) && $group->save())
            {
                # Return error
                return
                [
                    'data' =>
                    [
                        'success' => true,
                        'message' => 'Group was saved.',
                    ],
                    'code' => 0,
                ];
            }
            else
            {
                # Return error
                return
                [
                    'data' =>
                    [
                        'success' => false,
                        'message' => 'Group was not saved.',
                    ],
                    'code' => -1,
                ];
            }
        }

        # User got here by mistake (probably typed the URL in) set message
        \Yii::$app->session->setFlash('error', "Unfortunately I was unable to complete your last request.");

        # Send them back to the index
        return $this->redirect(URL::to('index'));
        //return $this->render('update');
    }
}

frontend/views/group/index.php
/**
 * This file is part of mnemosyne.
 *
 * mnemosyne is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * mnemosyne is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details
 * 
 * You should have received a copy of the GNU General Public License
 * long with mnemosyne.  If not, see <https://www.gnu.org/licenses/>.
**/

<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\spinner\Spinner;


echo "<h1>My Groups</h1>";

$addGroupForm = ActiveForm::begin(
[
    'action' => ['group/add'],
    'id' => 'add-group-form',
    'options' => ['class' => 'form-horizontal'],
]);


?>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6" style="width: 160px;">
            <?php echo $addGroupForm->field($this->params['group'], 'name')->textInput(['style'=>'width:150px']); ?>
        </div>
        <div class="col-sm-6" style="width: 155px;">
            <?php echo $addGroupForm->field($this->params['group'], 'description')->textInput(['style'=>'width:150px']); ?>
        </div>
        <div class="col-sm-6 pull-bottom" style="width: 155px;">
            <?php //echo $addCategoryForm->submit(); ?>
            <div class="form-group field-category-name required" style="padding-top: 27px">
                <!-- <label class="control-label"></label> -->
                <?php echo Html::submitButton('Add Group', ['class' => 'btn btn-primary', 'id' => 'addGroupBtnNoSpinner']) ?>
                <?php

                    echo '<button class="btn btn-primary hidden" id="addGroupBtnWithSpinner">';
                        echo Spinner::widget(['preset' => 'tiny', 'align' => 'right', 'caption' => 'Add Handle']);
                    echo '</button>';

                ?>
                <div class="help-block"></div>
            </div>
        </div>
    </div>
</div>
<?php
ActiveForm::end();


\yii\widgets\Pjax::begin();
//\yii\widgets\Pjax::widget(['id' => 'formsection']);
echo \yii\grid\GridView::widget(
[

  # Set ID
  'id' => 'group-grid',

	# Set dataprovider
  'dataProvider' => $this->params['groupDataProvider'],

	# Define columns
	'columns' =>
	[
        # Label
        [
            'class' => \yii2mod\editable\EditableColumn::class,
            'attribute' => 'name',
            'url' => ['group/update'],
        ],

		# Editable Handle
		[
			'class' => \yii2mod\editable\EditableColumn::class,
			'attribute' => 'description',
			'url' => ['group/update'],
		],

        # Group members
        [
            'label' => 'Members',
            'format' => 'raw',
            'value' => function ($model)
            {
                $output = "Click here to edit members";
                $members = $model->getGroupMembers()->all();
                if (count($members))
                {
                    $output = "";
                    foreach($members as $member)
                    {
                        $output .= "<li>".$member->getUser()->one()->email."</li>";
                    }
                }

                # Return
                return Html::a($output, ['groupmember/index', 'group_id' => $model->id], []);
            }
        ],

        # Delete
        [
            //'data-key' => function($data) {return $data->id;},
            'class' => 'yii\grid\ActionColumn',
            'template' => '{delete}',
            'buttons' =>
            [
                'delete' => function ()
                {
                    return Html::a('<span class="glyphicon glyphicon-trash"></span>', true,
                    [
                        'class' => 'pjax-delete-link',
                        'delete-url' => Url::toRoute('group/delete'),
                        'pjax-container' => 'group-grid',
                        'title' => Yii::t('yii', 'Delete')
                    ]);
                },
            ]
        ]
	]
]);
\yii\widgets\Pjax::end();
?>

frontend/views/group/view.php
/**
 * This file is part of mnemosyne.
 *
 * mnemosyne is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * mnemosyne is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details
 * 
 * You should have received a copy of the GNU General Public License
 * long with mnemosyne.  If not, see <https://www.gnu.org/licenses/>.
**/

<?php
/* @var $this yii\web\View */
?>
<h1>group/view</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>